import type { AuditAction } from '@kiotviet-lite/shared'

export const ACTION_LABELS: Record<AuditAction, string> = {
  login: 'Đăng nhập',
  'user.created': 'Tạo nhân viên',
  'user.updated': 'Sửa nhân viên',
  'user.locked': 'Khoá nhân viên',
  'user.unlocked': 'Mở khoá nhân viên',
  'user.pin_reset': 'Đặt lại mã PIN',
  'store.updated': 'Cập nhật cửa hàng',
  'auth.pin_failed': 'Nhập sai PIN',
  'auth.pin_locked': 'PIN bị khoá tạm thời',
  'category.created': 'Tạo danh mục',
  'category.updated': 'Sửa danh mục',
  'category.deleted': 'Xoá danh mục',
  'category.reordered': 'Sắp xếp danh mục',
  'brand.created': 'Tạo thương hiệu',
  'brand.updated': 'Sửa thương hiệu',
  'brand.deleted': 'Xoá thương hiệu',
  'brand.restored': 'Khôi phục thương hiệu',
  'product.created': 'Tạo sản phẩm',
  'product.updated': 'Sửa sản phẩm',
  'product.deleted': 'Xoá sản phẩm',
  'product.restored': 'Khôi phục sản phẩm',
  'product.stock_initialized': 'Khởi tạo tồn kho',
  'product.variant_created': 'Tạo biến thể',
  'product.variant_updated': 'Sửa biến thể',
  'product.variant_deleted': 'Xoá biến thể',
  'product.variants_enabled': 'Bật biến thể sản phẩm',
  'product.variants_disabled': 'Tắt biến thể sản phẩm',
  'product.unit_conversion_created': 'Tạo đơn vị quy đổi',
  'product.unit_conversion_updated': 'Sửa đơn vị quy đổi',
  'product.unit_conversion_deleted': 'Xoá đơn vị quy đổi',
  'inventory.purchase_recorded': 'Ghi nhận nhập hàng',
  'inventory.cost_recalculated': 'Tính lại giá vốn',
  'inventory.manual_adjusted': 'Điều chỉnh tồn kho thủ công',
  'customer.created': 'Tạo khách hàng',
  'customer.updated': 'Sửa khách hàng',
  'customer.deleted': 'Xoá khách hàng',
  'customer.restored': 'Khôi phục khách hàng',
  'customer_group.created': 'Tạo nhóm khách hàng',
  'customer_group.updated': 'Sửa nhóm khách hàng',
  'customer_group.deleted': 'Xoá nhóm khách hàng',
  'price_list.created': 'Tạo bảng giá',
  'price_list.updated': 'Sửa bảng giá',
  'price_list.deleted': 'Xoá bảng giá',
  'price_list.restored': 'Khôi phục bảng giá',
  'price_list.recalculated': 'Tính lại bảng giá',
  'price_list.cloned': 'Nhân bản bảng giá',
  'price_list.imported': 'Nhập danh sách giá',
  'price_list_item.created': 'Tạo dòng bảng giá',
  'price_list_item.updated': 'Sửa dòng bảng giá',
  'price_list_item.deleted': 'Xoá dòng bảng giá',
  'customer_price.created': 'Tạo giá riêng khách hàng',
  'customer_price.updated': 'Sửa giá riêng khách hàng',
  'customer_price.deleted': 'Xoá giá riêng khách hàng',
  'volume_prices.replaced': 'Cập nhật giá theo số lượng',
  'supplier.created': 'Tạo nhà cung cấp',
  'supplier.updated': 'Sửa nhà cung cấp',
  'supplier.deleted': 'Xoá nhà cung cấp',
  'supplier.restored': 'Khôi phục nhà cung cấp',
  'supplier.debt_changed': 'Cập nhật công nợ nhà cung cấp',
  'supplier_payment.created': 'Tạo phiếu chi',
  'supplier_debt_adjustment.created': 'Điều chỉnh công nợ nhà cung cấp',
  'supplier_debt.opening_created': 'Nạp nợ đầu kỳ nhà cung cấp',
  'purchase_order.created': 'Tạo phiếu nhập hàng',
  'stock_check.created': 'Tạo phiếu kiểm kê',
  'stock_check.updated': 'Sửa phiếu kiểm kê',
  'stock_check.confirmed': 'Xác nhận phiếu kiểm kê',
  'stock_check.deleted': 'Xoá phiếu kiểm kê',
  'order.created': 'Tạo đơn hàng',
  'category_discount.created': 'Tạo chiết khấu danh mục',
  'category_discount.updated': 'Sửa chiết khấu danh mục',
  'category_discount.deleted': 'Xoá chiết khấu danh mục',
  'order_item.price_overridden': 'Sửa giá trên đơn hàng',
  'debt.created': 'Tạo khoản nợ',
  'debt.opening_created': 'Nạp nợ đầu kỳ khách hàng',
  'debt.limit_overridden': 'Vượt hạn mức công nợ (PIN)',
  'order.debt_limit_exceeded': 'Đơn ngoại tuyến vượt hạn mức nợ',
  'order.price_mismatch_adjusted': 'Đơn ngoại tuyến điều chỉnh giá',
  'order.customer_mismatch_dropped': 'Đơn ngoại tuyến gỡ khách không thuộc cửa hàng',
  'order.discount_applied': 'Chiết khấu trên đơn',
  'order.approval_missing': 'Đơn ngoại tuyến thiếu duyệt giá, chiết khấu hoặc hạn mức',
  'order.policy_violation_offline': 'Đơn ngoại tuyến vi phạm chính sách, chờ duyệt',
  'order.review_approved': 'Duyệt đơn ngoại tuyến vi phạm chính sách',
  'order.review_rejected': 'Từ chối đơn ngoại tuyến vi phạm chính sách',
  'receipt.created': 'Tạo phiếu thu',
  'receipt.printed': 'In phiếu thu',
  'debt_adjustment.created': 'Điều chỉnh nợ khách hàng',
  'debt_ledger.backfilled': 'Điền ngược sổ công nợ R3',
  'order.returned': 'Trả hàng',
  'print_settings.updated': 'Cập nhật mẫu in',
  'receipt.cancelled': 'Hủy phiếu thu',
  'supplier_payment.cancelled': 'Hủy phiếu chi',
  'order.cancelled': 'Hủy đơn bán',
  'purchase_order.cancelled': 'Hủy phiếu nhập hàng',
  'purchase_return.created': 'Trả hàng nhập',
}

export interface ActionGroup {
  label: string
  actions: AuditAction[]
}

export const ACTION_GROUPS: ActionGroup[] = [
  {
    label: 'Nhân viên',
    actions: ['user.created', 'user.updated', 'user.locked', 'user.unlocked', 'user.pin_reset'],
  },
  {
    label: 'Cửa hàng',
    actions: ['store.updated'],
  },
  {
    label: 'Xác thực',
    actions: ['login', 'auth.pin_failed', 'auth.pin_locked'],
  },
  {
    label: 'Danh mục',
    actions: ['category.created', 'category.updated', 'category.deleted', 'category.reordered'],
  },
  {
    label: 'Thương hiệu',
    actions: ['brand.created', 'brand.updated', 'brand.deleted', 'brand.restored'],
  },
  {
    label: 'Sản phẩm',
    actions: [
      'product.created',
      'product.updated',
      'product.deleted',
      'product.restored',
      'product.stock_initialized',
      'product.variant_created',
      'product.variant_updated',
      'product.variant_deleted',
      'product.variants_enabled',
      'product.variants_disabled',
      'product.unit_conversion_created',
      'product.unit_conversion_updated',
      'product.unit_conversion_deleted',
    ],
  },
  {
    label: 'Tồn kho',
    actions: [
      'inventory.purchase_recorded',
      'inventory.manual_adjusted',
      'inventory.cost_recalculated',
    ],
  },
  {
    label: 'Khách hàng',
    actions: [
      'customer.created',
      'customer.updated',
      'customer.deleted',
      'customer.restored',
      'customer_group.created',
      'customer_group.updated',
      'customer_group.deleted',
    ],
  },
  {
    label: 'Bảng giá',
    actions: [
      'price_list.created',
      'price_list.updated',
      'price_list.deleted',
      'price_list.restored',
      'price_list.recalculated',
      'price_list.cloned',
      'price_list.imported',
      'price_list_item.created',
      'price_list_item.updated',
      'price_list_item.deleted',
      'customer_price.created',
      'customer_price.updated',
      'customer_price.deleted',
      'volume_prices.replaced',
    ],
  },
  {
    label: 'Nhà cung cấp',
    actions: [
      'supplier.created',
      'supplier.updated',
      'supplier.deleted',
      'supplier.restored',
      'supplier.debt_changed',
      'supplier_payment.created',
      'supplier_debt_adjustment.created',
      'supplier_debt.opening_created',
      'purchase_order.created',
      'purchase_order.cancelled',
      'purchase_return.created',
      'supplier_payment.cancelled',
    ],
  },
  {
    label: 'Kiểm kê',
    actions: [
      'stock_check.created',
      'stock_check.updated',
      'stock_check.confirmed',
      'stock_check.deleted',
    ],
  },
  {
    label: 'Đơn hàng',
    actions: ['order.created', 'order.returned', 'order.cancelled'],
  },
  {
    label: 'Chiết khấu danh mục',
    actions: [
      'category_discount.created',
      'category_discount.updated',
      'category_discount.deleted',
    ],
  },
  {
    label: 'Sửa giá POS',
    actions: ['order_item.price_overridden'],
  },
  {
    label: 'Công nợ',
    actions: [
      'debt.created',
      'debt.opening_created',
      'debt.limit_overridden',
      'order.debt_limit_exceeded',
      'debt_adjustment.created',
      'debt_ledger.backfilled',
    ],
  },
  {
    label: 'Phiếu thu',
    actions: ['receipt.created', 'receipt.printed', 'receipt.cancelled'],
  },
]

export function getActionLabel(action: string): string {
  return (ACTION_LABELS as Record<string, string>)[action] ?? action
}
